version: '3.8'

services:
  app:
    image: bloglist-front-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: bloglist-front-dev
  backend:
    image: bloglist-back-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    ports:
      - 3001:3001
    container_name: bloglist-back-dev
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend
